import hammerjs from 'hammerjs';
import slider from './modules/slider';
import modal from './modules/modal';
import menu from './modules/menu';
import forms from './modules/forms';
import validateInputs from './modules/validateInputs';
import showMoreStyles from './modules/showMoreStyles';
import tabs from './modules/tabs';
import replacePicture from './modules/replacePicture';
import accordion from './modules/accordion';
import dragDrop from './modules/dragDrop';
import smoothScroll from './modules/smoothScroll';
import calc from './modules/calc';
window.addEventListener('DOMContentLoaded', () => {
    'use strict';
    slider();
    modal();
    menu();
    forms();
    validateInputs();
    showMoreStyles();
    tabs();
    replacePicture();
    accordion();
    dragDrop();
    smoothScroll();
    calc();
});